### PR TITLE
Pseudoyaml

### PR DESCRIPTION
**Pull request by Fleker**
Using yaml to generate simple functions
Functions have custom inputs, read inputs,
return values, and set registers

### CODE REVIEW

**Comment by Fleker** [comment]
I'll admit that my examples of functions in the DAC aren't very good. This part of the spec may require some additional peripherals before it starts being useful.

**Comment by chrisfrederickson** [comment]
@Fleker the code here looks fine, but I think we need to rethink some of the PsudoYAML syntax.

Do we want functions to support setting multiple register values? The `send` value is something that wasn't obvious that it was necessary for setters until this example.

**Comment by Fleker** [comment]
Yes, we will need to think about setting many registers. This will become more apparent once we start working on higher-level functions like `init` and `reset`. In those cases, a simple `send` command will not work.

Additionally, the format of `functions` won't work either, as each function is tied to a specific register.

**Comment by Fleker** [comment]
Handled in future PRs. Closing this one.

**Pull request closed without merging**
