### PR TITLE
Create template for CMSIS SVD files

### PR DESCRIPTION
**Pull request by Fleker**
This change adds a new template and tests to verify resource generation

See #41

### CODE REVIEW

**Comment by Fleker** [comment]
FYI @chrisfrederickson and @proppy this is an example of how the files can be turned into other reference formats

**Comment by proppy** [comment]
Would it makes sense to support CMSIS SVD files as an alternative input format (instead of yaml)? This could allow you to leverage peripheral descriptions that are already authored in this format.

**Comment by Fleker** [comment]
No it wouldn't make sense as an input format, as the CMSIS SVD specification is not sufficient at providing every piece of information, notably in terms of endianness, unsigned/signed values, and most importantly logical computations for data conversions/processing.

**Comment by proppy** [comment]
For completeness:

> re: unsigned/signed value

The `register` [element](http://www.keil.com/pack/doc/CMSIS/SVD/html/elem_registers.html#elem_register), does seem to allow multiple signed/unsigned type.

> re: conversion/processing

The `register` element also have ` writeContraint` [sub-elements](http://www.keil.com/pack/doc/CMSIS/SVD/html/elem_registers.html#elem_writeConstraint), which seems to allow some conditional around write operation (albeit not open ended logic).

> re: endianness 

The `cpu` [element](https://arm-software.github.io/CMSIS_5/SVD/html/elem_cpu.html) does have a  `endian` sub element, but it seems global to the processor (not per peripheral). Maybe it's an artefact of the SVD spec being skewed toward describing CPU rather than arbitrary IC?

**Comment by Fleker** [comment]
There are some improvements that can be made, although the spec is very focused on CPUs in general such that it wouldn't be the perfect end output.

**Comment by proppy** [comment]
Would it change the answer to https://github.com/google/cyanobyte/pull/97#issuecomment-545264862 ?

**Comment by Fleker** [comment]
>  Maybe it's an artefact of the SVD spec being skewed toward describing CPU rather than arbitrary IC?

As SVD is generally skewed towards CPUs, it would not necessarily make sense as an input format as this project is skewed towards peripherals.

**Pull request merged**
