### PR TITLE
Refactor templates to language-specific directories

### PR DESCRIPTION
**Pull request by Fleker**
Rename templates directory to work with pip namespace

Rebased work from #262

### CODE REVIEW

**Comment by Fleker** [comment]
This doesn't work as-is because [resources](https://docs.python.org/3/library/importlib.html#importlib.resources.open_text) cannot have subdirectories.

**Comment by polfeliu** [comment]
Don't know what problem you have with folders. I think I was able to do it in cantata:
https://github.com/polfeliu/cantata/blob/8e4291407a9ac3ada48a380d0281cbcd327bc17e/cantata/main.py#L53

**Comment by Fleker** [comment]
Might be because you are pointing to the folder itself and not a file in a subdirectory.

**Comment by Fleker** [comment]
I'll merge this in now as the renaming will be useful ahead of a next release.

**Pull request merged**
